name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Check secrets
        run: echo ${{ secrets.PRIVATE_SSH_KEY }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 13.234.75.237
          username: ubuntu
          password: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            ls
            cd ci-cd-tut/
            git pull
            npm install
            npm run build
            pm2 run start
